name: Music Auto Update
on:
  schedule:
    - cron: '0 * * * *' # تشغيل تلقائي كل ساعة
  workflow_dispatch: # زر التشغيل اليدوي

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Requests
        run: pip install requests
      - name: Run Python Script
        run: python app.py # هنا تأكدنا من كتابة اسم ملفك app.py
      - name: Save Database
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add database.json
          git commit -m "Update Music List" || exit 0
          git push
          
